################################################################################## 
# STAGE 0 - base environment with first set of runtime dependencies 
##################################################################################
ARG BUILD_TAG
ARG GIT_COMMIT

FROM centos:centos7 as libprotobuf35x-lhdist-base-env

RUN yum -y --enablerepo=extras install epel-release && \
    yum -y install https://repo.ius.io/ius-release-el7.rpm && \
    yum clean all

##################################################################################
# STAGE 1 - build tools and libraries needed to build libprotobuf35x
##################################################################################
FROM libprotobuf35x-lhdist-base-env as libprotobuf35x-lhdist-build-env

# for compiling and unit testing
RUN yum -y install \
        cmake3 \
        gcc \
        gcc-c++ \
        gtest-devel \
        make \
        rpm-build && \
    yum clean all

# for building an rpm package
RUN yum -y install rpm-devel rpmlint bash coreutils diffutils patch rpmdevtools && \
    yum -y clean all

# for libprotobuf35x
RUN yum install -y \
        git \
        autoconf \
        libtool \
        make && \
    yum -y clean all

##################################################################################
# STAGE 2 - built and packaged libprotobuf35x
##################################################################################
FROM libprotobuf35x-lhdist-build-env as libprotobuf35x-lhdist-build

RUN mkdir -p /libprotobuf35x-lhdist

ADD ./modules/lhscriptutil/scripts/rpmdev-setuptree-at.sh /libprotobuf35x-lhdist
ADD ./dist/libprotobuf35x-lhdist.spec /libprotobuf35x-lhdist

RUN cd /libprotobuf35x-lhdist && \
    mkdir build && \
    ./rpmdev-setuptree-at.sh ./build && \
    rpmbuild --define "_topdir ${PWD}/build"  -ba ./libprotobuf35x-lhdist.spec && \
    mkdir -p /lhdist && \
    find ./build/RPMS/ | grep "\.rpm" | xargs -I{} cp -f -u {} /lhdist

ENV BUILD_TAG=${BUILD_TAG}
LABEL build_tag="${BUILD_TAG}"
ENV GIT_COMMIT=${GIT_COMMIT}
LABEL git_commit="${GIT_COMMIT}"

##################################################################################
# STAGE 3 - test /lhdist
##################################################################################
FROM libprotobuf35x-lhdist-build-env as libprotobuf35x-lhdist-check

ADD ./modules/lhscriptutil/scripts/refreshOrSetupLHDistYumRepo.sh /refreshOrSetupLHDistYumRepo.sh
RUN /refreshOrSetupLHDistYumRepo.sh
RUN yum -y repo-pkgs lhdistrepo install && \
    yum clean all

##################################################################################
# STAGE 4 - package in /lhdist
##################################################################################
FROM libprotobuf35x-lhdist-base-env as libprotobuf35x-lhdist-dist

COPY --from=libprotobuf35x-lhdist-build /lhdist /lhdist