STAT( FailedPublisherReceives )
STAT( NotificationsReceived )
STAT( NotificationsProcessed )
STAT( NotificationsFailed )
STAT( FailedSendSubsriptions )
STAT( FailedControllerReceives )
STAT( MalformedCommandMessages )
STAT( UnknownControllerCommand )
